project_id = "wkwztjpvtsmwvgumywfi"

[functions.create-student-accounts]
verify_jwt = true

[functions.get-users-with-roles]
verify_jwt = true

[functions.create-admin-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.check-default-password]
verify_jwt = true

[functions.reset-password-by-email]
verify_jwt = true
